import { MockDatabase } from "./MockDatabase";
import { Model } from "./client/Model";
export { sql } from "./client/sql";
const database = new MockDatabase({"palette_":{"id": {"type":"bigint","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null},"name": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null},"thumbnail_colors": {"type":"text[]","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null},"raw_css": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null}},"project_":{"id": {"type":"uuid","modifierPrimaryKey":true,"modifierNotNull":true,"modifierDefault":true,"reference":null},"palette_id": {"type":"bigint","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":true,"reference":{"tableName":"palette_","columnName":"id"}},"prompt": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null},"public": {"type":"boolean","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":true,"reference":null}},"preview_":{"id": {"type":"bigint","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null},"project_id": {"type":"uuid","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":{"tableName":"project_","columnName":"id"}},"version": {"type":"smallint","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":true,"reference":null},"prompt": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null},"code": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null},"thumbnail_src": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null}}});
type PaletteData = {
  id: number | null;
  name: string;
  thumbnail_colors: Array<string> | null;
  raw_css: string;
}
type PaletteAutoGenerated = never;
type PaletteOptional = never;
type PaletteRelationship = {
}
export const palette = new Model<PaletteData, PaletteAutoGenerated, PaletteOptional, PaletteRelationship>("palette_", database);
type ProjectData = {
  id: string;
  palette_id: number;
  prompt: string;
  public: boolean | null;
}
type ProjectAutoGenerated = "id";
type ProjectOptional = "id"|"palette_id"|"public";
type ProjectRelationship = {
  palette_id: PaletteData;
}
export const project = new Model<ProjectData, ProjectAutoGenerated, ProjectOptional, ProjectRelationship>("project_", database);
type PreviewData = {
  id: number | null;
  project_id: string;
  version: string | null;
  prompt: string;
  code: string | null;
  thumbnail_src: string | null;
}
type PreviewAutoGenerated = never;
type PreviewOptional = "version";
type PreviewRelationship = {
  project_id: ProjectData;
}
export const preview = new Model<PreviewData, PreviewAutoGenerated, PreviewOptional, PreviewRelationship>("preview_", database);